# Generated by Django 5.0.4 on 2024-05-05 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("collection", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MuseumObject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="", max_length=50)),
                (
                    "ccObjectID",
                    models.CharField(db_index=True, default="", max_length=50),
                ),
                ("index_name", models.CharField(default="", max_length=50)),
            ],
        ),
    ]
