# Generated by Django 5.0.4 on 2024-05-05 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collection", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="museumobject",
            name="api_lastmodified",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="museumobject",
            name="plone_timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
