# Generated by Django 5.0.4 on 2024-05-05 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collection", "0003_museumobject_api_lastmodified_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="museumobject",
            name="synced",
            field=models.BooleanField(null=True),
        ),
    ]
