# Generated by Django 5.0.4 on 2024-05-05 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collection", "0005_synclock"),
    ]

    operations = [
        migrations.AddField(
            model_name="synclock",
            name="sync_switch",
            field=models.CharField(default="sync_switch", max_length=50),
        ),
    ]
