# Generated by Django 5.0.4 on 2024-05-07 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collection", "0006_synclock_sync_switch"),
    ]

    operations = [
        migrations.AddField(
            model_name="synclock",
            name="stop_requested",
            field=models.BooleanField(default=False),
        ),
    ]
