# Generated by Django 5.0.4 on 2024-05-10 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collection", "0007_synclock_stop_requested"),
    ]

    operations = [
        migrations.AlterField(
            model_name="museumobject",
            name="title",
            field=models.CharField(blank=True, default="", max_length=50, null=True),
        ),
    ]
