# Generated by Django 5.0.4 on 2024-05-10 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collection", "0008_alter_museumobject_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="ObjectLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("log_message", models.TextField()),
                (
                    "museum_object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="collection.museumobject",
                    ),
                ),
            ],
        ),
    ]
